language: node_js
node_js: "stable"
install:
  - npm install
script:
  - npm test
env:
  - NODE_ENV=test
cache:
  directories:
    - "node_modules"
branches: 
  only:
    - "develop"
services:
  - postgresql
before_script: 
  - psql -c 'create database IF NOT EXISTS travis;' -U postgres
after_success:
  - npm run coverage
